package com.ace.trade.mapper;

import com.ace.trade.entity.TradeCoupon;
import com.ace.trade.entity.TradeCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    long countByExample(TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int deleteByExample(TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int deleteByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int insert(TradeCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int insertSelective(TradeCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    List<TradeCoupon> selectByExample(TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    TradeCoupon selectByPrimaryKey(String couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") TradeCoupon record, @Param("example") TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int updateByExample(@Param("record") TradeCoupon record, @Param("example") TradeCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int updateByPrimaryKeySelective(TradeCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int updateByPrimaryKey(TradeCoupon record);
}