package com.ace.trade.mapper;

import com.ace.trade.entity.TradeMqProducerTemp;
import com.ace.trade.entity.TradeMqProducerTempExample;
import com.ace.trade.entity.TradeMqProducerTempKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeMqProducerTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    long countByExample(TradeMqProducerTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    int deleteByExample(TradeMqProducerTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    int deleteByPrimaryKey(TradeMqProducerTempKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    int insert(TradeMqProducerTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    int insertSelective(TradeMqProducerTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    List<TradeMqProducerTemp> selectByExample(TradeMqProducerTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    TradeMqProducerTemp selectByPrimaryKey(TradeMqProducerTempKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") TradeMqProducerTemp record, @Param("example") TradeMqProducerTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    int updateByExample(@Param("record") TradeMqProducerTemp record, @Param("example") TradeMqProducerTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    int updateByPrimaryKeySelective(TradeMqProducerTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    int updateByPrimaryKey(TradeMqProducerTemp record);
}