package com.ace.trade.mapper;

import com.ace.trade.entity.TradeMqConsumerLog;
import com.ace.trade.entity.TradeMqConsumerLogExample;
import com.ace.trade.entity.TradeMqConsumerLogKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeMqConsumerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    long countByExample(TradeMqConsumerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    int deleteByExample(TradeMqConsumerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    int deleteByPrimaryKey(TradeMqConsumerLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    int insert(TradeMqConsumerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    int insertSelective(TradeMqConsumerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    List<TradeMqConsumerLog> selectByExample(TradeMqConsumerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    TradeMqConsumerLog selectByPrimaryKey(TradeMqConsumerLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") TradeMqConsumerLog record, @Param("example") TradeMqConsumerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    int updateByExample(@Param("record") TradeMqConsumerLog record, @Param("example") TradeMqConsumerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    int updateByPrimaryKeySelective(TradeMqConsumerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    int updateByPrimaryKey(TradeMqConsumerLog record);
}