package com.ace.trade.mapper;

import com.ace.trade.entity.TradeUser;
import com.ace.trade.entity.TradeUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    long countByExample(TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int deleteByExample(TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int insert(TradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int insertSelective(TradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    List<TradeUser> selectByExample(TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    TradeUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") TradeUser record, @Param("example") TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int updateByExample(@Param("record") TradeUser record, @Param("example") TradeUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int updateByPrimaryKeySelective(TradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_user
     *
     * @mbg.generated Sat Sep 01 23:12:45 CST 2018
     */
    int updateByPrimaryKey(TradeUser record);
}