package com.ace.trade.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TradeCoupon implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_coupon.coupon_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private String couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_coupon.coupon_price
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private BigDecimal couponPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_coupon.user_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_coupon.oder_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private String oderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_coupon.is_used
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private String isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_coupon.used_time
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private Date usedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_coupon.coupon_id
     *
     * @return the value of trade_coupon.coupon_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public String getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_coupon.coupon_id
     *
     * @param couponId the value for trade_coupon.coupon_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public void setCouponId(String couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_coupon.coupon_price
     *
     * @return the value of trade_coupon.coupon_price
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public BigDecimal getCouponPrice() {
        return couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_coupon.coupon_price
     *
     * @param couponPrice the value for trade_coupon.coupon_price
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public void setCouponPrice(BigDecimal couponPrice) {
        this.couponPrice = couponPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_coupon.user_id
     *
     * @return the value of trade_coupon.user_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_coupon.user_id
     *
     * @param userId the value for trade_coupon.user_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_coupon.oder_id
     *
     * @return the value of trade_coupon.oder_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public String getOderId() {
        return oderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_coupon.oder_id
     *
     * @param oderId the value for trade_coupon.oder_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public void setOderId(String oderId) {
        this.oderId = oderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_coupon.is_used
     *
     * @return the value of trade_coupon.is_used
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public String getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_coupon.is_used
     *
     * @param isUsed the value for trade_coupon.is_used
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public void setIsUsed(String isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_coupon.used_time
     *
     * @return the value of trade_coupon.used_time
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public Date getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_coupon.used_time
     *
     * @param usedTime the value for trade_coupon.used_time
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", couponId=").append(couponId);
        sb.append(", couponPrice=").append(couponPrice);
        sb.append(", userId=").append(userId);
        sb.append(", oderId=").append(oderId);
        sb.append(", isUsed=").append(isUsed);
        sb.append(", usedTime=").append(usedTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TradeCoupon other = (TradeCoupon) that;
        return (this.getCouponId() == null ? other.getCouponId() == null : this.getCouponId().equals(other.getCouponId()))
            && (this.getCouponPrice() == null ? other.getCouponPrice() == null : this.getCouponPrice().equals(other.getCouponPrice()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOderId() == null ? other.getOderId() == null : this.getOderId().equals(other.getOderId()))
            && (this.getIsUsed() == null ? other.getIsUsed() == null : this.getIsUsed().equals(other.getIsUsed()))
            && (this.getUsedTime() == null ? other.getUsedTime() == null : this.getUsedTime().equals(other.getUsedTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_coupon
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCouponId() == null) ? 0 : getCouponId().hashCode());
        result = prime * result + ((getCouponPrice() == null) ? 0 : getCouponPrice().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOderId() == null) ? 0 : getOderId().hashCode());
        result = prime * result + ((getIsUsed() == null) ? 0 : getIsUsed().hashCode());
        result = prime * result + ((getUsedTime() == null) ? 0 : getUsedTime().hashCode());
        return result;
    }
}