package com.ace.trade.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class TradePay implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pay.pay_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private String payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pay.order_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pay.pay_amount
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private BigDecimal payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pay.is_paid
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private String isPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_pay
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pay.pay_id
     *
     * @return the value of trade_pay.pay_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pay.pay_id
     *
     * @param payId the value for trade_pay.pay_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public void setPayId(String payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pay.order_id
     *
     * @return the value of trade_pay.order_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pay.order_id
     *
     * @param orderId the value for trade_pay.order_id
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pay.pay_amount
     *
     * @return the value of trade_pay.pay_amount
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pay.pay_amount
     *
     * @param payAmount the value for trade_pay.pay_amount
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pay.is_paid
     *
     * @return the value of trade_pay.is_paid
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public String getIsPaid() {
        return isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pay.is_paid
     *
     * @param isPaid the value for trade_pay.is_paid
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    public void setIsPaid(String isPaid) {
        this.isPaid = isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", payId=").append(payId);
        sb.append(", orderId=").append(orderId);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", isPaid=").append(isPaid);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TradePay other = (TradePay) that;
        return (this.getPayId() == null ? other.getPayId() == null : this.getPayId().equals(other.getPayId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getPayAmount() == null ? other.getPayAmount() == null : this.getPayAmount().equals(other.getPayAmount()))
            && (this.getIsPaid() == null ? other.getIsPaid() == null : this.getIsPaid().equals(other.getIsPaid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_pay
     *
     * @mbg.generated Sat Sep 01 21:47:27 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPayId() == null) ? 0 : getPayId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getPayAmount() == null) ? 0 : getPayAmount().hashCode());
        result = prime * result + ((getIsPaid() == null) ? 0 : getIsPaid().hashCode());
        return result;
    }
}