package com.ace.trade.entity;

import java.io.Serializable;
import java.util.Date;

public class TradeMqProducerTemp extends TradeMqProducerTempKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_producer_temp.msg_body
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    private String msgBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_producer_temp.create_time
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_producer_temp.msg_body
     *
     * @return the value of trade_mq_producer_temp.msg_body
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    public String getMsgBody() {
        return msgBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_producer_temp.msg_body
     *
     * @param msgBody the value for trade_mq_producer_temp.msg_body
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_producer_temp.create_time
     *
     * @return the value of trade_mq_producer_temp.create_time
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_producer_temp.create_time
     *
     * @param createTime the value for trade_mq_producer_temp.create_time
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", msgBody=").append(msgBody);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TradeMqProducerTemp other = (TradeMqProducerTemp) that;
        return (this.getGroupName() == null ? other.getGroupName() == null : this.getGroupName().equals(other.getGroupName()))
            && (this.getMsgTag() == null ? other.getMsgTag() == null : this.getMsgTag().equals(other.getMsgTag()))
            && (this.getMsgKeys() == null ? other.getMsgKeys() == null : this.getMsgKeys().equals(other.getMsgKeys()))
            && (this.getMsgBody() == null ? other.getMsgBody() == null : this.getMsgBody().equals(other.getMsgBody()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_producer_temp
     *
     * @mbg.generated Sat Oct 20 11:34:54 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGroupName() == null) ? 0 : getGroupName().hashCode());
        result = prime * result + ((getMsgTag() == null) ? 0 : getMsgTag().hashCode());
        result = prime * result + ((getMsgKeys() == null) ? 0 : getMsgKeys().hashCode());
        result = prime * result + ((getMsgBody() == null) ? 0 : getMsgBody().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}