package com.ace.trade.entity;

import java.io.Serializable;

public class TradeMqConsumerLog extends TradeMqConsumerLogKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.msg_id
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    private String msgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.msg_body
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    private String msgBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.consumer_status
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    private String consumerStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.consumer_times
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    private Integer consumerTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_mq_consumer_log.remark
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.msg_id
     *
     * @return the value of trade_mq_consumer_log.msg_id
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.msg_id
     *
     * @param msgId the value for trade_mq_consumer_log.msg_id
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.msg_body
     *
     * @return the value of trade_mq_consumer_log.msg_body
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    public String getMsgBody() {
        return msgBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.msg_body
     *
     * @param msgBody the value for trade_mq_consumer_log.msg_body
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    public void setMsgBody(String msgBody) {
        this.msgBody = msgBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.consumer_status
     *
     * @return the value of trade_mq_consumer_log.consumer_status
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    public String getConsumerStatus() {
        return consumerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.consumer_status
     *
     * @param consumerStatus the value for trade_mq_consumer_log.consumer_status
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    public void setConsumerStatus(String consumerStatus) {
        this.consumerStatus = consumerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.consumer_times
     *
     * @return the value of trade_mq_consumer_log.consumer_times
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    public Integer getConsumerTimes() {
        return consumerTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.consumer_times
     *
     * @param consumerTimes the value for trade_mq_consumer_log.consumer_times
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    public void setConsumerTimes(Integer consumerTimes) {
        this.consumerTimes = consumerTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_mq_consumer_log.remark
     *
     * @return the value of trade_mq_consumer_log.remark
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_mq_consumer_log.remark
     *
     * @param remark the value for trade_mq_consumer_log.remark
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", msgId=").append(msgId);
        sb.append(", msgBody=").append(msgBody);
        sb.append(", consumerStatus=").append(consumerStatus);
        sb.append(", consumerTimes=").append(consumerTimes);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TradeMqConsumerLog other = (TradeMqConsumerLog) that;
        return (this.getGroupName() == null ? other.getGroupName() == null : this.getGroupName().equals(other.getGroupName()))
            && (this.getMsgTag() == null ? other.getMsgTag() == null : this.getMsgTag().equals(other.getMsgTag()))
            && (this.getMsgKeys() == null ? other.getMsgKeys() == null : this.getMsgKeys().equals(other.getMsgKeys()))
            && (this.getMsgId() == null ? other.getMsgId() == null : this.getMsgId().equals(other.getMsgId()))
            && (this.getMsgBody() == null ? other.getMsgBody() == null : this.getMsgBody().equals(other.getMsgBody()))
            && (this.getConsumerStatus() == null ? other.getConsumerStatus() == null : this.getConsumerStatus().equals(other.getConsumerStatus()))
            && (this.getConsumerTimes() == null ? other.getConsumerTimes() == null : this.getConsumerTimes().equals(other.getConsumerTimes()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_mq_consumer_log
     *
     * @mbg.generated Mon Oct 15 23:03:48 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getGroupName() == null) ? 0 : getGroupName().hashCode());
        result = prime * result + ((getMsgTag() == null) ? 0 : getMsgTag().hashCode());
        result = prime * result + ((getMsgKeys() == null) ? 0 : getMsgKeys().hashCode());
        result = prime * result + ((getMsgId() == null) ? 0 : getMsgId().hashCode());
        result = prime * result + ((getMsgBody() == null) ? 0 : getMsgBody().hashCode());
        result = prime * result + ((getConsumerStatus() == null) ? 0 : getConsumerStatus().hashCode());
        result = prime * result + ((getConsumerTimes() == null) ? 0 : getConsumerTimes().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}